server {
    listen 80;
    server_name localhost;

    # 1. Configuración principal para React (SPA)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Si la ruta no existe, carga index.html (necesario para React Router)
        try_files $uri $uri/ /index.html;
    }

    # 2. Configuración para los archivos compilados (CSS, JS, Imágenes)
    # Esto evita que el 'try_files' de arriba rompa tus estilos
    location /assets/ {
        root /usr/share/nginx/html;
        # Aseguramos el tipo MIME correcto
        include /etc/nginx/mime.types;
        expires 1y;
        add_header Cache-Control "public";
    }
}