# Usamos una imagen ligera de Node.js
FROM node:20-alpine

# Creamos el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiamos los archivos de dependencias
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código (el server.js)
COPY . .

# Exponemos el puerto en el que corre nuestra app
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["node", "server.js"]